# -*- coding: utf-8 -*-
"""Assignment-5(I).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzXri4yAbcRGFrMipXdHeIASkbYa9eaJ
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
len = 100

#Plotting circle
O=np.array([4,0])
r=4
theta = np.linspace(0,2*np.pi,len)
x_circ = np.zeros((2,len))
x_circ[0,:] = r*np.cos(theta)
x_circ[1,:] = r*np.sin(theta)
x_circ = (x_circ.T + O).T
plt.plot(x_circ[0,:],x_circ[1,:],label='$x^2+y^2-8x=0$')

plt.plot(O[0], O[1], 'o')
plt.text(O[0] * (1 + 0.1), O[1] * (1 - 0.1) , 'O')

# Generating points
A = np.array([0,0])
B = np.array([8,0])
C = np.array([4,4])
l = np.array([4,4.8])
m = np.array([4,-4.8])
r = np.array([-2,0])
s = np.array([10,0])

#Plotting points
plt.plot(A[0], A[1], 'o')
plt.text(0.2, 0.2 , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(8.2, 0.2, 'B')
plt.plot(C[0], C[1], 'o')
plt.text(4.2,4.2, 'C')

# Generating lines
x_lm = line_gen(l,m)
x_rs = line_gen(r,s)

#Plotting all lines
plt.plot(x_lm[0,:],x_lm[1,:])
plt.plot(x_rs[0,:],x_rs[1,:])

# Plotting parabola
y = np.linspace(-5,5,100)
x=(y*y)/4
plt.plot(x,y,label='$y^2=4x$')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()